### PR TITLE
Adding popup js

### PR DESCRIPTION
**Pull request by Androx27**
Since this is an offline web app, we should adding a standalone javascript instead

### CODE REVIEW

**Comment by Androx27** [comment]
hold on, there's something wrong, the sub menu couldn't be collapsed
maybe there's some files that we needed for making it worked

**Comment by ryumada** [comment]
I think @Mock1ng didn't make the sub menu can be collapsed after the user open it.

**Review by ryumada — COMMENTED** [review]
I will try it first

**Comment by ryumada** [comment]
> hold on, there's something wrong, the sub menu couldn't be collapsed
> maybe there's some files that we needed for making it worked

pls make this on issue section. @Androx27

**Review by ryumada — APPROVED** [review]

**Pull request merged**
